### ISSUE TITLE
package.json exports does not match updated file casing

### ISSUE THREAD

**Issue by zfghterb721** [jessealama/decimal128#112]
In #111, `./src/decimal128.mts` was renamed to `./src/Decimal128.mts`, along with other files. Although the code references throughout the codebase were updated accordingly, the changes were not reflected in package.json, resulting in a broken npm package.

### **Suggested Fix:**
Update package.json to reflect the renamed file ./src/Decimal128.mts.

**Comment by jessealama** [comment]
This should be fixed now. Thanks!
